modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"

[[mods]]
modId="nethelurgy"
version="0.2.1"
displayName="Nethelurgy"
logoFile="nethelurgy.png"
authors="SkellaTex"
description='''Adds new ores, resources, and improves upon the Nether'''

[[dependencies.nethelurgy]]
    modId="forge"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.nethelurgy]]
    modId="minecraft"
    mandatory=true
    versionRange="1.20.1"
    ordering="NONE"
    side="BOTH"
